FROM python:3.9-slim

WORKDIR /usr/src/app

# Install the dependencies specified in requirements.txt
RUN pip install --no-cache-dir pandas matplotlib seaborn

# Command to run your app
CMD ["python"]
